# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/grpc_mod/proto/user.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'src/grpc_mod/proto/user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dsrc/grpc_mod/proto/user.proto\x12\x05proto\"n\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\ndiscord_id\x18\x02 \x01(\x03\x12\x0e\n\x06\x61vatar\x18\x03 \x01(\t\x12\x10\n\x08username\x18\x04 \x01(\t\x12\x15\n\rdiscriminator\x18\x05 \x01(\t\x12\r\n\x05\x65mail\x18\x06 \x01(\t\"P\n\x0eGetUserRequest\x12\x0f\n\x02id\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x17\n\ndiscord_id\x18\x02 \x01(\x03H\x01\x88\x01\x01\x42\x05\n\x03_idB\r\n\x0b_discord_id\"m\n\x0fPostUserRequest\x12\x12\n\ndiscord_id\x18\x01 \x01(\x03\x12\x0e\n\x06\x61vatar\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t\x12\x15\n\rdiscriminator\x18\x04 \x01(\t\x12\r\n\x05\x65mail\x18\x05 \x01(\t\"\xd6\x01\n\x10\x41lterUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x17\n\ndiscord_id\x18\x02 \x01(\x03H\x00\x88\x01\x01\x12\x13\n\x06\x61vatar\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x15\n\x08username\x18\x04 \x01(\tH\x02\x88\x01\x01\x12\x1a\n\rdiscriminator\x18\x05 \x01(\tH\x03\x88\x01\x01\x12\x12\n\x05\x65mail\x18\x06 \x01(\tH\x04\x88\x01\x01\x42\r\n\x0b_discord_idB\t\n\x07_avatarB\x0b\n\t_usernameB\x10\n\x0e_discriminatorB\x08\n\x06_email\"\x1f\n\x11\x44\x65leteUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"%\n\x12\x44\x65leteUserResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xe3\x01\n\x0bUserService\x12-\n\x07GetUser\x12\x15.proto.GetUserRequest\x1a\x0b.proto.User\x12/\n\x08PostUser\x12\x16.proto.PostUserRequest\x1a\x0b.proto.User\x12\x31\n\tAlterUser\x12\x17.proto.AlterUserRequest\x1a\x0b.proto.User\x12\x41\n\nDeleteUser\x12\x18.proto.DeleteUserRequest\x1a\x19.proto.DeleteUserResponseB1Z/github.com/KuramaSyu/WerSu-Rest/src/proto;protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.grpc_mod.proto.user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z/github.com/KuramaSyu/WerSu-Rest/src/proto;proto'
  _globals['_USER']._serialized_start=40
  _globals['_USER']._serialized_end=150
  _globals['_GETUSERREQUEST']._serialized_start=152
  _globals['_GETUSERREQUEST']._serialized_end=232
  _globals['_POSTUSERREQUEST']._serialized_start=234
  _globals['_POSTUSERREQUEST']._serialized_end=343
  _globals['_ALTERUSERREQUEST']._serialized_start=346
  _globals['_ALTERUSERREQUEST']._serialized_end=560
  _globals['_DELETEUSERREQUEST']._serialized_start=562
  _globals['_DELETEUSERREQUEST']._serialized_end=593
  _globals['_DELETEUSERRESPONSE']._serialized_start=595
  _globals['_DELETEUSERRESPONSE']._serialized_end=632
  _globals['_USERSERVICE']._serialized_start=635
  _globals['_USERSERVICE']._serialized_end=862
# @@protoc_insertion_point(module_scope)
